name: schema_org_flutter
description: "A flexible, dynamic Schema.org JSON-LD Framework and UI Engine for Dart & Flutter."
version: 0.1.0
homepage: https://github.com/schemaorg/schemaorg

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/schemaorg-current-https.jsonld
