name: Publish Flutter Package & Deploy Web Demo

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish_dry_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Package Publishing Status
        run: flutter pub publish --dry-run

  deploy_demo_web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Example App Web Demo
        run: |
          cd example
          flutter pub get
          flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy Demo to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
